site_name: Sandstorm
pages:
- "Home": "index.md"
- Intro:
    - "Overview": "overview.md"
    - "Installation": "install.md"
    - "Guided tour": "guided-tour.md"
- App packaging:
    - "Overview of vagrant-spk": "vagrant-spk/index.md"
    - "Installation": "vagrant-spk/installation.md"
    - "Packaging tutorial": "vagrant-spk/packaging-tutorial.md"
    - "Understanding & customizing": "vagrant-spk/customizing.md"
    - "Platform stacks": "vagrant-spk/platform-stacks.md"
