site_name: Sandstorm
theme: 'readthedocs'
pages:
- "Home": "index.md"
- Using:
    - "Overview": "using.md"
    - "Guided tour": "guided-tour.md"
    - "Top bar": "using/top-bar.md"
- Developing:
    - "Overview": "developing.md"
    - "Technical overview": "overview.md"
    - "Overview of vagrant-spk": "vagrant-spk/index.md"
    - "Installation": "vagrant-spk/installation.md"
    - "Packaging tutorial": "vagrant-spk/packaging-tutorial.md"
    - "User authentication & permissions": "developing/auth.md"
    - "Understanding & customizing": "vagrant-spk/customizing.md"
    - "Platform stacks": "vagrant-spk/platform-stacks.md"
    - "Code dependencies": "vagrant-spk/code-dependencies.md"
    - "Services": "vagrant-spk/services.md"
    - "Web publishing": "developing/web-publishing.md"
    - "Email from apps": "developing/email-from-apps.md"
    - "vagrant-spk design document": "vagrant-spk/design.md"
    - "Raw packaging guide": "developing/raw-packaging-guide.md"
    - "Raw integration of Python": "developing/raw-python.md"
    - "Raw integration of Ruby on Rails": "developing/raw-ruby-on-rails.md"
    - "Troubleshooting": "developing/troubleshooting.md"
- Admistering:
    - "Overview": "administering.md"
    - "Installation": "install.md"
    - "Email": "administering/email.md"
    - "Demo mode": "administering/demo.md"
    - "Backups": "administering/backups.md"
    - "Wildcard hosts": "administering/wildcard.md"
    - "Frequently asked questions": "administering/faq.md"
